build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-irc
    when:
      branch: master


plugin:
  name: IRC
  desc: Sends build status notifications to your IRC channel.
  type: notify
  image: plugins/drone-irc
  labels:
    - chat
    - messaging
