build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-irc
    when:
      branch: master

plugin:
  name: IRC
  desc: Send build status notifications via IRC
  type: notify
  image: plugins/drone-irc
  labels:
    - chat
    - messaging
    - irc
