build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-irc
    when:
      branch: master


plugin:
  name: IRC
  desc: Sends build status notifications to your IRC channel.
  type: notify
  image: plugins/drone-irc
  labels:
    - chat
    - messaging
