[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-template-lib"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/thoj/go-ircevent"
  version = "0.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
